config/routes.rb
Rails.application.routes.draw do
  root 'search#category'
  namespace :search do
    get 'keyword'
    get 'category'
  end
  namespace :admin do
    resources :categories, only: [:index] do
      patch 'bulk_update', on: :collection
      post 'import', on: :collection
    end
    resources :meta_tags, only: [:index, :create, :destroy] do
      patch 'bulk_update', on: :collection
      post 'import', on: :collection
      post 'add_property'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
require 'csv'

class Category < ApplicationRecord
  has_ancestry

  def self.import!(file)
    update_attributes = %w(id name rakuten_id yahoo_id ancestry)
    CSV.foreach(file.path, headers: true) do |row|
      category = find_by(id: row['id']) || new
      category.attributes = row.to_hash.slice(*update_attributes)
      category.save
    end
  end
end

app/models/meta_tag.rb
class MetaTag < ApplicationRecord
  has_many :properties, class_name: 'MetaTagProperty', dependent: :destroy
  accepts_nested_attributes_for :properties, allow_destroy: true

  def self.import!(file)
    CSV.foreach(file.path, headers: true) do |row|
      if row['table_name'] == 'meta_tags'
        update_attributes = %w(id name)
        meta_tag = find_by(id: row['id']) || new
        meta_tag.attributes = row.to_hash.slice(*update_attributes)
        meta_tag.save!
      elsif row['table_name'] == 'meta_tag_properties'
        update_attributes = %w(id name value meta_tag_id)
        meta_tag = find_by(id: row['meta_tag_id']) || new
        property = meta_tag.properties.find_by(id: row['id']) || meta_tag.properties.new
        property.attributes = row.to_hash.slice(*update_attributes)
        property.save!
      end
    end
  end
end

app/models/meta_tag_property.rb
class MetaTagProperty < ApplicationRecord
  belongs_to :meta_tag, foreign_key: :meta_tag_id
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :basic_auth, if: :production?

  def production?
    Rails.env.production?
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |user_name, password|
      user_name == Rails.application.credentials.basic_auth[:user_name] && password == Rails.application.credentials.basic_auth[:password]
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  def index
    respond_to do |format|
      format.html do
        @root_categories = Category.roots
      end
      format.csv do
        @categories = Category.all
      end
    end
  end

  def bulk_update
    categories_params.to_h.map do |id, param|
      category = Category.find(id)
      category.update!(param)
    end
    redirect_to action: :index
  end

  def import
    Category.import!(params[:file])
    redirect_to action: :index
  end

  private

  def categories_params
    params.permit(categories: [:name, :rakuten_id, :yahoo_id])[:categories]
  end
end

app/controllers/admin/meta_tags_controller.rb
class Admin::MetaTagsController < Admin::ApplicationController

  def index
    @meta_tags = MetaTag.includes(:properties)
    respond_to do |format|
      format.html do
      end
      format.csv do
      end
    end
  end

  def create
    meta_tag = MetaTag.create
    meta_tag.properties.create
    redirect_to action: :index
  end

  def add_property
    MetaTag.find(params[:meta_tag_id]).properties.create
    redirect_to action: :index
  end

  def destroy
    MetaTag.find(params[:id]).destroy
    redirect_to action: :index
  end

  def bulk_update
    meta_tags_params.to_h.map do |id, param|
      meta_tag = MetaTag.find(id)
      meta_tag.update!(param)
    end
    redirect_to action: :index
  end

  def import
    MetaTag.import!(params[:file])
    redirect_to action: :index
  end

  private

  def meta_tags_params
    params.permit(meta_tags: [:name, { properties_attributes: [:id, :name, :value] }])[:meta_tags]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def keyword
    @categories = Category.where(ancestry: nil)
    @rakuten_items = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword]).to_a
    @yahoo_shopping_items = YahooShoppingWebService::Item.search(query: params[:keyword])
    render :index
  end

  def category
    @category = Category.find(params[:category_id] || 1)
    @categories = categories(@category)
    @rakuten_items = RakutenWebService::Ichiba::Genre[@category.rakuten_id].ranking.to_a
    @yahoo_shopping_items = YahooShoppingWebService::Category.ranking(@category.yahoo_id || 2494)
    render :index
  end

  private

  def categories(category)
    categories = params[:category_id].present? ? category.children : Category.where(ancestry: nil)
    categories = category.siblings if categories.blank?
    categories
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def yahoo_shopping_item_info(itemcode)
    YahooShoppingWebService::Item.lookup(itemcode)
  end

  def category_info(category_id)
    YahooShoppingWebService::Category.search(category_id)
  end

  def yahoo_shopping_item_url(item)
    return item.image.medium if action_name == 'keyword'

    item.Image.Medium
  end

  def yahoo_shopping_item_price(item)
    return item.price if action_name == 'keyword'

    item = yahoo_shopping_item_info(item.Code)
    item&.Hit&.Price
  end

  def categories_breadcrumb(category)
    return if category.nil?

    categoriy_paths = category.path.map do |c|
      link_to c.name, search_category_path(category_id: c.id)
    end
    categoriy_paths.join(' / ').html_safe
  end

  def meta_tags
    meta_tags = MetaTag.all.map do |meta_tag|
      properties = meta_tag.properties.map { |property| "#{property.name}=#{property.value}" }.join(' ')
      "<meta name=#{meta_tag.name} #{properties}>"
    end
    meta_tags.join("\n").html_safe
  end
end

app/views/admin/categories/index.html.erb
<!-- SECTION -->
<div class="section">
  <!-- container -->
  <div class="container">
    <!-- row -->
    <div class="row">
      <%= form_with url: import_admin_categories_path do |f| %>
        <%= f.file_field :file %>
        <%= submit_tag "インポート" %>
      <% end %>
      <%= button_to 'エクスポート', admin_categories_path(format: :csv), method: :get %>
      <div style="display: flex;">
        <% @root_categories.each do |root| %>
          <div>
            <%= form_with url: bulk_update_admin_categories_path, method: :patch do |f| %>
              <table>
                <thead>
                  <tr>
                    <td>カテゴリー名</td>
                    <td>楽天ID</td>
                    <td>ヤフーID</td>
                  </tr>
                </thead>
                <tbody>
                  <%= f.fields_for "categories[]", root do |ff| %>
                    <tr>
                      <td><%= ff.text_field :id, value: root.id, disabled: true %></td>
                      <td><%= ff.text_field :name, value: root.name %></td>
                      <td><%= ff.text_field :rakuten_id, value: root.rakuten_id %></td>
                      <td><%= ff.text_field :yahoo_id, value: root.yahoo_id %></td>
                      <td><%= ff.text_field :ancestry, value: root.ancestry, disabled: true %></td>
                    </tr>
                  <% end %>
                  <tr></tr>
                  <% root.descendants.each do |children| %>
                    <%= f.fields_for "categories[]", children do |ff| %>
                      <tr>
                        <td><%= ff.text_field :id, value: children.id, disabled: true %></td>
                        <td><%= ff.text_field :name, value: children.name %></td>
                        <td><%= ff.text_field :rakuten_id, value: children.rakuten_id %></td>
                        <td><%= ff.text_field :yahoo_id, value: children.yahoo_id %></td>
                        <td><%= ff.text_field :ancestry, value: children.ancestry, disabled: true %></td>
                      </tr>
                    <% end %>
                  <% end %>
                </tbody>
              </table>
              <%= f.submit '更新' %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/meta_tags/index.html.erb
<!-- SECTION -->
<div class="section">
  <!-- container -->
  <div class="container">
    <!-- row -->
    <div class="row">
      <%= form_with url: import_admin_meta_tags_path do |f| %>
        <%= f.file_field :file %>
        <%= submit_tag "インポート" %>
      <% end %>
      <%= button_to 'エクスポート', admin_meta_tags_path(format: :csv), method: :get %>
      <%= button_to 'タグ追加', admin_meta_tags_path, method: :post %>
      <%= form_with url: bulk_update_admin_meta_tags_path, method: :patch do |f| %>
        <table>
          <tbody>
            <% @meta_tags.each do |meta_tag| %>
              <tr>
                <%= f.fields_for "meta_tags[]", meta_tag do |ff| %>
                  <td>
                    <%= '<meta ' %>
                    name="<%= ff.text_field :name, value: meta_tag.name %>"
                    <% meta_tag.properties.each.with_index(1) do |property, i| %>
                      <%= ff.hidden_field :id, value: property.id, name: "[meta_tags][#{meta_tag.id}][[properties_attributes][#{property.id}][id]]" %>
                      <%= ff.text_field "[properties_attributes][#{property.id}][name]", value: property.name %>="<%= ff.text_field "[properties_attributes][#{property.id}][value]", value: property.value %>"
                    <% end %>
                    >
                  </td>
                <% end %>
                <td><button><%= link_to '属性追加', admin_meta_tag_add_property_path(meta_tag.id), method: :post %></button></td>
                <td><button><%= link_to '削除', admin_meta_tag_path(meta_tag), method: :delete %></button></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= f.submit '更新' %>
      <% end %>
    </div>
  </div>
</div>

<style>
  td {
    vertical-align: top;
  }
</style>

app/views/search/index.html.erb
<!-- NAVIGATION -->
<nav id="navigation">
  <!-- container -->
  <div class="container">
    <!-- responsive-nav -->
    <div id="responsive-nav">
      <!-- NAV -->
      <!-- <ul class="main-nav nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">Hot Deals</a></li>
        <li><a href="#">Categories</a></li>
        <li><a href="#">Laptops</a></li>
        <li><a href="#">Smartphones</a></li>
        <li><a href="#">Cameras</a></li>
        <li><a href="#">Accessories</a></li>
      </ul> -->
      <!-- /NAV -->
    </div>
    <!-- /responsive-nav -->
  </div>
  <!-- /container -->
</nav>
<!-- /NAVIGATION -->

<!-- BREADCRUMB -->
<div id="breadcrumb" class="section">
  <!-- container -->
  <div class="container">
    <!-- row -->
    <!-- <div class="row">
      <div class="col-md-12">
        <ul class="main-nav nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">Hot Deals</a></li>
          <li><a href="#">Categories</a></li>
          <li><a href="#">Laptops</a></li>
          <li><a href="#">Smartphones</a></li>
          <li><a href="#">Cameras</a></li>
          <li><a href="#">Accessories</a></li>
        </ul>
      </div>
    </div> -->
    <!-- /row -->
  </div>
  <!-- /container -->
</div>
<!-- /BREADCRUMB -->

<!-- SECTION -->
<div class="section">
  <!-- container -->
  <div class="container">
    <!-- row -->
    <div class="row">
      <!-- ASIDE -->
      <div id="aside" class="col-md-3">
        <!-- aside Widget -->
        <div class="aside">
          <h3 class="aside-title">Categories</h3>
          <div style="font-size: smaller; margin-bottom: 10px"><%= categories_breadcrumb(@category) %></div>
          <div class="checkbox-filter">
          <% @categories.each do |category| %>
            <div class="input-checkbox">
              <label for="category-1">
                <div id="category_<%= category.id %>"><%= link_to category.name, search_category_path(category_id: category.id), style: params[:category_id] == category.id.to_s ? 'color: #D10024;' : '' %></div>
              </label>
            </div>
          <% end %>
          </div>
        </div>
        <!-- /aside Widget -->
      </div>
      <!-- /ASIDE -->

      <!-- STORE -->
      <div id="store" class="col-md-9">
        <!-- store top filter -->
        <div class="store-filter clearfix">
          <!-- SEARCH BAR -->
          <div>
            <div class="header-search">
              <%= form_with url: search_keyword_path, method: :get %>
                <input class="input" name="keyword" placeholder="Search here" value="<%= params[:keyword] %>">
                <button class="search-btn">Search</button>
              </form>
            </div>
          </div>
          <!-- /SEARCH BAR -->
        </div>
        <!-- /store top filter -->

        <!-- store products -->
        <div class="row">
          <div class="col-md-4" style="text-align: center;">
            楽天市場
          </div>
          <div class="col-md-4" style="text-align: center;">
            Yahoo!ショッピング
          </div>
          <div class="col-md-4" style="text-align: center;">
            Amazon
          </div>
        <% (0..4).each do |i| %>
          <!-- product -->
          <div class="col-md-4 col-xs-6">
            <a href="<%= @rakuten_items[i]['affiliateUrl'] %>" target="_blank" rel="noopener noreferrer">
              <div class="product">
                <div class="product-img">
                  <%= image_tag @rakuten_items[i].medium_image_urls.first || 'http://placehold.jp/262x262.png' %>
                  <div class="product-label">
                    <% if action_name == 'category' %><span class="new"><%= i + 1 %>位</span><% end %>
                  </div>
                </div>
                <div class="product-body">
                  <p class="product-category"><%= @rakuten_items[i].genre.name %></p>
                  <h3 class="product-name"><%= @rakuten_items[i]['itemName'] %></h3>
                  <h4 class="product-price"><%= number_to_currency(@rakuten_items[i]['itemPrice'], precision: 0, unit: '') %>円</h4>
                  <div class="product-rating">
                    <i class='fa fa-star'></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                  </div>
                </div>
              </div>
            </a>
          </div>
          <!-- /product -->

          <!-- product -->
          <div class="col-md-4 col-xs-6">
            <a href="<%= @yahoo_shopping_items[i].url || @yahoo_shopping_items[i].Url %>" target="_blank" rel="noopener noreferrer">
              <div class="product">
                <div class="product-img">
                  <%= image_tag yahoo_shopping_item_url(@yahoo_shopping_items[i]) || 'http://placehold.jp/262x262.png' %>
                  <div class="product-label">
                    <% if action_name == 'category' %><span class="new"><%= i + 1 %>位</span><% end %>
                  </div>
                </div>
                <div class="product-body">
                  <p class="product-category"><%= @yahoo_shopping_items[i].genreCategory&.name || @category.name %></p>
                  <h3 class="product-name"><%= @yahoo_shopping_items[i].name %></h3>
                  <h4 class="product-price"><%= number_to_currency(yahoo_shopping_item_price(@yahoo_shopping_items[i]), precision: 0, unit: '').presence || '????' %>円</h4>
                  <div class="product-rating">
                    <i class='fa fa-star'></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                  </div>
                </div>
              </div>
            </a>
          </div>
          <!-- /product -->

          <div class="clearfix visible-sm visible-xs"></div>

          <!-- product -->
          <div class="col-md-4 col-xs-6">
            <a href="#" target="_blank" rel="noopener noreferrer">
              <div class="product">
                <div class="product-img">
                  <%= image_tag 'http://placehold.jp/262x262.png' %>
                  <div class="product-label">
                    <% if action_name == 'category' %><span class="new"><%= i + 1 %>位</span><% end %>
                  </div>
                </div>
                <div class="product-body">
                  <p class="product-category">&nbsp;</p>
                  <h3 class="product-name">&nbsp;</h3>
                  <h4 class="product-price">&nbsp;</h4>
                  <div class="product-rating">
                    <i class='fa fa-star'></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                  </div>
                </div>
              </div>
            </a>
          </div>
          <!-- /product -->
        <% end %>
        </div>
        <!-- /store products -->

        <!-- store bottom filter -->
        <!-- <div class="store-filter clearfix">
          <span class="store-qty">Showing 20-100 products</span> -->
          <!-- <ul class="store-pagination">
            <li class="active">1</li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i></a></li>
          </ul> -->
        <!-- </div> -->
        <!-- /store bottom filter -->
      </div>
      <!-- /STORE -->
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div>
<!-- /SECTION -->

<!-- NEWSLETTER -->
<!-- <div id="newsletter" class="section"> -->
  <!-- container -->
  <!-- <div class="container"> -->
    <!-- row -->
    <!-- <div class="row">
      <div class="col-md-12">
        <div class="newsletter">
          <p>Sign Up for the <strong>NEWSLETTER</strong></p>
          <form>
            <input class="input" type="email" placeholder="Enter Your Email">
            <button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
          </form>
          <ul class="newsletter-follow">
            <li>
              <a href="#"><i class="fa fa-facebook"></i></a>
            </li>
            <li>
              <a href="#"><i class="fa fa-twitter"></i></a>
            </li>
            <li>
              <a href="#"><i class="fa fa-instagram"></i></a>
            </li>
            <li>
              <a href="#"><i class="fa fa-pinterest"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div> -->
    <!-- /row -->
  <!-- </div> -->
  <!-- /container -->
<!-- </div> -->
<!-- /NEWSLETTER -->